# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: skillscout_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: skillscout_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./backend/migrations/seed_glints_jobs.sql:/docker-entrypoint-initdb.d/02-seed.sql

  backend:
    image: skillscout_backend_img
    build:
      context: ./backend
    container_name: skillscout_backend
    restart: always
    depends_on:
      - db
      - ml-service
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:supersecretpassword@db:5432/skillscout_db
      - ML_SERVICE_URL=http://ml-service:8001
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app # Hot-reload untuk development
    # Uncomment baris di bawah ini jika menggunakan Traefik sebagai reverse proxy nantinya
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.backend.rule=Host(`api.skillscout.local`)"

  ml-service:
    image: skillscout_ml_img
    build:
      context: ./ml-service
    container_name: skillscout_ml
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - ./ml-service:/app
    environment:
      - PORT=8001
      - ALLOWED_ORIGINS=*

  frontend:
    image: skillscout_frontend_img
    build:
      context: ./frontend
    container_name: skillscout_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app # Hot-reload untuk development
      - /app/node_modules
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.frontend.rule=Host(`skillscout.local`)"

volumes:
  postgres_data:
